### ISSUE TITLE
Add support for DB2 cluster

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/charts#16]
**Is your feature request related to a problem? Please describe.**
Need artifacts to deploy a cluster of DB2 instances.

**Describe the solution you'd like**
Similar to https://github.com/Senzing/rancher-demo but using 3 DB2 instances instead of a single mySQL.

**Comment by docktermj** [comment]
Test comment.

**Comment by kernelsam** [comment]
Repo is being archived, closing.
